stages:
  load_data: 
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/campusplacement.csv
    outs:
    - data/raw/campusplacement.csv
  split_data:
   cmd: python src/split_data.py --config=params.yaml
   deps:
   - src/split_data.py
   - data/raw/campusplacement.csv
   outs: 
   - data/processed/train_campusplacement.csv
   - data/processed/test_campusplacement.csv
   