base:
  project: campusplacement
  random_state: 30
  target_col: status

data_source:
  s3_source: data_given/campusplacement.csv
  

load_data:
  raw_dataset_csv: data/raw/campusplacement.csv



split_data:
  train_path: data/processed/train_campusplacement.csv
  test_path: data/processed/test_campusplacement.csv
  test_size: 0.2

estimators:
  # RandomForestClassifier-:
  #   params:
  #     max_depth: 10
  #     max_leaf_nodes: 2
  # LogisticRegression:
  #   params:
  #     n_jobs: 2
  # Knn:
  #   params:
  #     n_neighbors: 4
  #     algorithm: kd_tree
  DecisionTreeClassifier:
    params:
      max_depth: 10
      max_leaf_nodes: 2

    metrics:
      - reports/scores.json:
          cache: false
      - reports/params.json:
          cache: false


model_dir: saved_models


reports:
  params: reports/params.json
  scores: reports/scores.json