base:
  project: campusplacement
  random_state: 30
  target_col: status

data_source:
  s3_source: data_given/campus.csv
  

load_data:
  raw_dataset_csv: data/raw/campus.csv

transformed_data:
  transformed_data_csv: data/transformed/campus_transformed.csv

split_data:
  train_path: data/processed/train_campus.csv
  test_path: data/processed/test_campus.csv

estimators:
  LogisticRegression:
    n_jobs: 2
  Knn:
    n_neighbors: 4
    algorithm: kd_tree
  DecisionTree:
    max_depth: 10
    max_leaf_nodes: 2

model_dir: saved_models
